---
- name: Retrieve committed configuration
  hosts: juniper_devices
  roles:
    - Juniper.junos
  connection: local
  gather_facts: false
  # gather facts from control node (here)

  vars:
    user: "{{ ansible_user }}"
    passwd: "{{ ansible_password }}"

  tasks:
    - name: Retrieve srx commited configuration
      juniper_junos_config:
        retrieve: "committed"
        dest_dir: "configuration_backups_vcs/{{ inventory_hostname }}"
        # dest: "configuration_backups_vcs/{{ inventory_hostname }}/{{ inventory_hostname }}-.conf"
          # the above can also be used to specify filename, and manipulate with date etc if req.
      register: response
