---
- name: Compare and commit configuration backups
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
#================================
    - name: "Git: is it up-to-date?"
      git:
        repo: XXX@github.com:GITHUB_USERNAME/REPO_NAME
        dest: /PATH/TO/WORKING/DIR
        update: yes
        version: master
      register: git
      ignore_errors: true
    - debug:
        var: git
#================================
    - name: Git - Adding
      shell: "git add *"
      args:
        chdir: /PATH/TO/WORKING/DIR/configuration_backups_vcs
      register: gitadd
      when: git.msg is defined
    - debug:
        var: gitadd.cmd
#================================
    - name: Git - commiting
      shell: git commit -m "Ansible Backup" 
      args:
        chdir: /PATH/TO/WORKING/DIR/configuration_backups_vcs
      register: gitcommit
      when: git.msg is defined
    - debug:
        var: gitcommit.stdout
#================================  
    - name: Git - push
      shell: git push 
      args:
        chdir: /PATH/TO/WORKING/DIR/configuration_backups_vcs
      register: gitpush
      when: git.msg is defined
    - debug: